# Generated by Django 6.0.2 on 2026-03-07 14:53

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_update_role_choices_and_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='page_permissions',
            field=models.JSONField(default=accounts.models.default_page_permissions),
        ),
    ]
